# Generated by Django 3.0.5 on 2020-04-30 08:43

from django.db import migrations, models
import import_csv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixationData',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.IntegerField()),
                ('StimuliName', models.FilePathField(
                    path=import_csv.models.stimuli_path)),
                ('FixationIndex', models.IntegerField()),
                ('FixationDuration', models.IntegerField()),
                ('MappedFixationPointX', models.IntegerField()),
                ('MappedFixationPointY', models.IntegerField()),
                ('user', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
