# Generated by Django 3.0.5 on 2020-04-30 08:43

from django.db import migrations, models
import import_csv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('stimuli_name', models.FilePathField(path=import_csv.models.stimuli_path)),
                ('fixation_index', models.IntegerField()),
                ('fixation_duration', models.IntegerField()),
                ('mapped_fixation_point_X', models.IntegerField()),
                ('mapped_fixation_point_Y', models.IntegerField()),
                ('user', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
